
obj-$(CONFIG_IOPLUS_RPI) 			:= ioplus_rpi-core.o
obj-$(CONFIG_IOPLUS_RPI_I2C)		+= ioplus_rpi-i2c.o
obj-$(CONFIG_IOPLUS_RPI_GPIO)		+= ioplus_rpi-gpio.o
obj-$(CONFIG_IOPLUS_RPI_RELAY)		+= ioplus_rpi-relay.o
obj-$(CONFIG_IOPLUS_RPI_IIO)		+= ioplus_rpi-iio.o
obj-$(CONFIG_IOPLUS_RPI_PWM)		+= pwm-ioplus_rpi.o


	

	
